gpu_num: 0 # 在指定编号的gpu上训练
device: cuda # 此项不用修改

train:
  batch_size: 16
  epochs: 1000
  num_workers: 4

model:
  rnn_hidden: 256
  kernel_num: (32, 64, 128, 256, 256, 256)

# optim
optimizer: Adam
learning_rate: 0.001
weight_decay: 0.   #regular

# scheduler
scheduler:
  factor: 0.5
  patience: 3
  verbose: y

# model path
model_path: ./output
load_model:

# VoiceBank-DEMAND Corpus (VCTK)
VCTK_dataset:
  path: D:/PycharmProjects/DATASETS/VoiceBank+DEMAND
  trainset: ./wavs_path/VoiceBank+DEMAND/trainset-shuffle.txt
  testset: ./wavs_path/VoiceBank+DEMAND/testset.txt
  wav_dur: 3

# Deep Xi dataset
DeepXi_dataset:
#  path: D:\PycharmProjects\DATASETS\deep_xi_dataset
#  train_clean_files: train_clean_speech.txt
#  train_noise_files: train_noise.txt
#  validate_files: val_clean_speech.txt
#  test_files: test_clean_speech.txt
#  test_snrs: (-5, 0, 5, 10, 15)
#  wav_dur: 3